name: the_youtube_player
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  meta: '>=1.7.0 <2.0.0'
  webview_flutter: ^4.0.2
  webview_flutter_android: ^3.2.1
  webview_flutter_wkwebview: ^3.0.2
  # url_launcher: ^6.1.8
  youtube_player_iframe_web: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/player.html

  plugin:
    platforms:
      web:
        default_package: youtube_player_iframe_web

platforms:
  android:
  ios:
  web: