name: the_youtube_player
description: "A new Flutter package project."
version: 1.0.0
# homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.0




dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
  - assets/speedometer.webp

platforms:
  android:
  ios:
